my_string = input("Как вас зовут: ")
string = len(my_string)
print("Количество символов: ", string)
print(my_string. upper())
print(my_string. lower())
print(my_string. replace(" ",""))
print(my_string[0])
print(my_string[-1])